name: Build and Deploy DSPM Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            comnyang/backend:latest
            comnyang/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-northeast-2 \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Rollout restart backend
        run: |
          kubectl rollout restart deployment dspm-backend -n dspm

      - name: Verify deployment
        run: |
          kubectl rollout status deployment dspm-backend -n dspm --timeout=300s